module.exports = [
  {
    name: "Serengeti National Park",
    coords: { lat: -2.3333, lng: 34.8333 },
    type: "terrestrial",
    animalId: 1,
    animals: ["African Lion"],
    description: "Great Migration.",
  },
  {
    name: "Kruger National Park",
    coords: { lat: -24.0667, lng: 31.4833 },
    type: "terrestrial",
    animalId: 4,
    animals: ["Asian Elephant"],
    description: "Big 5 safari.",
  },
  {
    name: "Masai Mara",
    coords: { lat: -1.5, lng: 35.8333 },
    type: "terrestrial",
    animalId: 5,
    animals: ["Giraffe"],
    description: "Migration corridor.",
  },
  {
    name: "Great Barrier Reef",
    coords: { lat: -18.2871, lng: 147.6992 },
    type: "marine",
    animalId: 11,
    animals: ["Vaquita"],
    description: "Largest coral reef.",
  },
  {
    name: "Sea of Cortez",
    coords: { lat: 28.5, lng: -112 },
    type: "marine",
    animalId: 12,
    animals: ["Dugong"],
    description: "Marine biodiversity.",
  },
  {
    name: "Ningaloo Reef",
    coords: { lat: -22.6667, lng: 113.6667 },
    type: "marine",
    animalId: 15,
    animals: ["Whale Shark"],
    description: "Whale shark aggregation.",
  },
  {
    name: "Pantanal Wetlands",
    coords: { lat: -16.2667, lng: -56.6667 },
    type: "freshwater",
    animalId: 13,
    animals: ["Axolotl"],
    description: "Largest wetland.",
  },
  {
    name: "Lake Xochimilco",
    coords: { lat: 19.25, lng: -99.1 },
    type: "freshwater",
    animalId: 14,
    animals: ["Golden Poison Frog"],
    description: "Axolotl habitat.",
  },
  {
    name: "Okavango Delta",
    coords: { lat: -19.0344, lng: 22.3667 },
    type: "freshwater",
    animals: ["Hippo"],
    description: "Inland delta oasis.",
  },
  {
    name: "Komodo National Park",
    coords: { lat: -8.5435, lng: 119.4956 },
    type: "terrestrial",
    animalId: 6,
    animals: ["Komodo Dragon"],
    description: "Dragon island.",
  },
  {
    name: "Madagascar Rainforest",
    coords: { lat: -20.25, lng: 47 },
    type: "terrestrial",
    animalId: 9,
    animals: ["Cobra"],
    description: "Island endemics.",
  },
  {
    name: "Galapagos Islands",
    coords: { lat: -0.5, lng: -90.5 },
    type: "terrestrial",
    animalId: 3,
    animals: ["Green Sea Turtle"],
    description: "Darwin's laboratory.",
  },
  {
    name: "Denali National Park",
    coords: { lat: 63.0694, lng: -151.0072 },
    type: "terrestrial",
    animalId: 8,
    animals: ["Polar Bear"],
    description: "Mount Denali.",
  },
  {
    name: "Himalayan Highlands",
    coords: { lat: 28.3949, lng: 84.1426 },
    type: "terrestrial",
    animals: ["Snow Leopard"],
    description: "High altitude.",
  },
  {
    name: "Andes Cloud Forest",
    coords: { lat: -2.2, lng: -77.9 },
    type: "terrestrial",
    animalId: 16,
    animals: ["Smalltooth Sawfish"],
    description: "Mountain biodiversity.",
  },
];
